version: '3.0'

services:       
    postgres:
        container_name: postgres
        build: ./study-postgres
        restart: always
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    server:
        container_name: server
        build: ./study-nest
        restart: always
        volumes: 
            - ./study-nest:/home/node/app
        ports:
            - "3000:3000"