name: 'my_new_project'          # dbt project name
version: '1.0.0'                # dbt project version
config-version: 2

profile: 'snowflakeTutorial'         # ~/.dbt/profiles.ymlからデータベースに接続するために使用するプロファイルの名前を示します

source-paths: ["models"]        # モデルを作成するためにスクリプトを保存するディレクトリを示します
analysis-paths: ["analysis"]    
test-paths: ["tests"]
data-paths: ["data"]            # dbtがシードデータを検索するディレクトリを示します。
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"           # モデルとUIのファイルを作成するためにコンパイルされたSQLスクリプトを保存するディレクトリを示します。
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  my_new_project:
      materialized: table
      staging:
        materialized: view
