version: '3.0'

services:      
    postgresdb:
        container_name: postgresdb
        build: ./ttc-study-db
        restart: always
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    server:
        container_name: server
        build: ./ttc-study
        restart: always
        volumes: 
            - ./ttc-study:/home/node/app
        ports:
            - "8888:3000"
        depends_on: 
            - postgresdb