version: '3.8'

services:      
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    server:
        container_name: server
        build: 
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        depends_on: 
            - postgres