version: '3.0'

services: 
    prisma:
        image: prismagraphql/prisma:1.34
        container_name: prisma
        restart: always
        ports:
            - '${PRISMA_PORT}:${PRISMA_PORT}'
        environment:
            PRISMA_CONFIG: |
                managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
                port: ${PRISMA_PORT}
                databases:
                    default:
                        connector: postgres
                        host: postgres
                        port: ${POSTGRES_PORT}
                        user: ${POSTGRES_USER}
                        password: ${POSTGRES_PASSWORD}
                        database: ${POSTGRES_DB}  
    postgres:
        build: ./db_postgres
        container_name: postgres
        restart: always
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    server:
        container_name: server
        build: ./nestjs_prisma
        restart: always
        volumes: 
            - ./nestjs_prisma:/home/node/app
        ports:
            - "8888:3000"